CREATE TABLE topics(
    id SERIAL PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    alias VARCHAR(24) NOT NULL,
    content TEXT,
    email VARCHAR(24) NOT NULL,
    secret BIGINT NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE replies(
    id SERIAL PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    alias VARCHAR(24) NOT NULL,
    content TEXT,
    email VARCHAR(24) NOT NULL,
    secret BIGINT NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
